env:
  global:
    - CC_TEST_REPORTER_ID=e2ca993c4bcda4f766cd71566e224de37c084c49bf282c70dbcd8133c01f03af
    - RYOGIFT_CLIENT_URL=https://ryo.gift
    - ADMIN_EMAIL=admin@ryo.gift
    - ADMIN_PASSWORD=password
language: ruby
rvm: 2.7.0
services: postgresql
bundler_args: "--without development --deployment -j4"
cache: bundler
before_script:
  - cp config/database.travis.yml config/database.yml
  - bundle exec rails db:setup
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script: bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
