default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ryogift_api_development
test:
  <<: *default
  database: ryogift_api_test
production:
  <<: *default
  database: ryogift_api_production
  username: ryogift_api
  password: <%= ENV['RYOGIFT_API_DATABASE_PASSWORD'] %>
